# Generated by Django 3.1.1 on 2020-09-18 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20200918_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='spouse_firstname',
            new_name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='spouse_lastname',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 21, 26, 11, 906838)),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 21, 26, 11, 906838)),
        ),
    ]
