# Generated by Django 3.1.1 on 2020-09-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20200918_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_registered',
            field=models.DateField(default='September 20, 2020 09:27:17'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default='September 20, 2020 09:27:17'),
        ),
    ]
