# Generated by Django 3.1.1 on 2020-09-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20200919_1725'),
        ('customer', '0017_auto_20200920_1346'),
    ]

    operations = [
    ]
