# Generated by Django 3.1.1 on 2020-09-21 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20200920_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 9, 21, 17, 31, 39, 320134)),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
