# Generated by Django 3.1.1 on 2020-09-21 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20200921_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 9, 21, 17, 34, 6, 206788)),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
