# Generated by Django 3.1.1 on 2020-09-23 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20200921_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 9, 23, 18, 37, 27, 575836)),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
