# Generated by Django 3.1.1 on 2020-09-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20200920_2305'),
        ('customer', '0021_auto_20200921_2144'),
    ]

    operations = [
    ]
