# Generated by Django 3.1.1 on 2020-09-24 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_merge_20200921_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 9, 24, 23, 16, 9, 662221)),
        ),
    ]
