# Generated by Django 3.1.1 on 2020-09-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_auto_20200923_1949'),
        ('customer', '0022_merge_20200921_2312'),
    ]

    operations = [
    ]
