# Generated by Django 3.1.1 on 2020-09-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_auto_20200924_1733'),
        ('customer', '0023_auto_20200924_2316'),
    ]

    operations = [
    ]
