# Generated by Django 3.1.1 on 2020-10-10 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_merge_20200928_2047'),
        ('customer', '0027_merge_20200925_1916'),
    ]

    operations = [
    ]
