# Generated by Django 3.1.1 on 2020-10-10 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_merge_20201010_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 21, 18, 49, 362397)),
        ),
    ]
