# Generated by Django 3.1.1 on 2020-10-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_auto_20201011_1100'),
        ('customer', '0031_auto_20201011_1347'),
    ]

    operations = [
    ]
