# Generated by Django 3.1.1 on 2020-09-18 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('sku', models.AutoField(primary_key=True, serialize=False, verbose_name='SKU')),
                ('title', models.CharField(default='Untitled DVD', max_length=50)),
                ('date_registered', models.DateField(default=datetime.datetime.now)),
                ('director', models.CharField(blank=True, max_length=50)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('casts', models.CharField(blank=True, max_length=500)),
                ('price', models.FloatField(default=0)),
                ('number_of_items', models.IntegerField(default=0)),
                ('picture', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'DVD',
            },
        ),
    ]
