# Generated by Django 3.1.1 on 2020-09-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='date_registered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='release_date',
            field=models.DateField(blank=True),
        ),
    ]
