# Generated by Django 3.1.1 on 2020-09-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0003_auto_20200920_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
