# Generated by Django 3.1.1 on 2020-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0004_auto_20200920_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='picture',
            field=models.FileField(upload_to='dvd_images/'),
        ),
    ]
