# Generated by Django 3.1.1 on 2020-10-10 21:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0029_auto_20201010_2118'),
        ('dvd', '0006_auto_20200924_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rented', models.DateField(default=datetime.datetime(2020, 10, 10, 21, 18, 49, 365651))),
                ('no_of_items', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('dvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvd.dvd')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
