# Generated by Django 3.1.1 on 2020-10-11 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_rented',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 11, 0, 34, 373388)),
        ),
    ]
