# Generated by Django 3.1.1 on 2020-10-11 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201010_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_rented',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 13, 46, 58, 325623)),
        ),
    ]
