# Generated by Django 3.1.1 on 2020-10-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201011_1100'),
        ('order', '0003_auto_20201011_1347'),
    ]

    operations = [
    ]
